name: Unzip and Deploy
on: [push]

jobs:
  unzip:
    runs-on: ubuntu-latest
    permissions:  # 🔥 WICHTIG: Füge diese Berechtigungen hinzu!
      contents: write
    steps:
      - uses: actions/checkout@v2

      - name: Unzip DEMO_ZEDTECH.zip
        run: |
          unzip -o DEMO_ZEDTECH.zip -d .  # 🔥 Name exakt anpassen!

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Automatisch entpackt: DEMO_ZEDTECH.zip"
          git push
